# -*- mode: ruby -*-
# vi: set ft=ruby :

servers = [
    {
        :name => "v-k8s-master",
        :type => "master",
        :box => "ubuntu/focal64",
        :eth1 => "192.168.99.10",
        :mem => "2048",
        :cpu => "2"
    },
    {
        :name => "v-k8s-worker-01",
        :type => "worker",
        :box => "ubuntu/focal64",
        :eth1 => "192.168.99.11",
        :mem => "1024",
        :cpu => "2"
    },
    {
        :name => "v-k8s-worker-02",
        :type => "worker",
        :box => "ubuntu/focal64",
        :eth1 => "192.168.99.12",
        :mem => "1024",
        :cpu => "2"
    }
]

Vagrant.configure("2") do |config|
    servers.each do |opts|
        config.vm.define opts[:name] do |config|
            config.vm.box = opts[:box]
            config.vm.hostname = opts[:name]

            # By default, private networks are host-only networks
            # https://www.vagrantup.com/docs/providers/virtualbox/networking
            config.vm.network "private_network", ip: opts[:eth1]

            config.vm.provider "virtualbox" do |v|
                v.name = opts[:name]
            	v.customize ["modifyvm", :id, "--groups", "/group__v-kube-cluster"]
                v.customize ["modifyvm", :id, "--memory", opts[:mem]]
                v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
            end

            # to prevent tty errors
            config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
            config.vm.provision "shell", path: "provision/common.sh"

            if opts[:type] == "master"
                config.vm.provision "shell", path: "provision/master.sh"
                config.vm.network "forwarded_port", guest: 8001, host: 8001
                config.vm.network "forwarded_port", guest: 8080, host: 8080
            else
                config.vm.provision "shell", path: "provision/worker.sh"
            end
        end
    end
end
